apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ev-key-auth
  namespace: candy-services
plugin: key-auth
config:
  key_names:
    - X-API-KEY
  hide_credentials: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ev-rate-limit
  namespace: candy-services
plugin: rate-limiting
config:
  minute: 120
  hour: 5000
  policy: local
  fault_tolerant: true
  hide_client_headers: false
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: ev-internal
  namespace: candy-services
  annotations:
    kubernetes.io/ingress.class: kong
username: ev-internal
credentials:
  - ev-apikey-credential
