{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "euro-virtuals.fullname" . }}-netpol
  namespace: candy-services
spec:
  podSelector:
    matchLabels:
      {{- include "euro-virtuals.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kong
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: candy-services
      ports:
        - port: 8080
  egress:
    - {}
{{- end }}
