apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metabase-db-secret
  namespace: metabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: metabase-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: metabase_db_credentials
        property: DB_PASSWORD
