apiVersion: v2
name: tpay
description: TPay Django 4.2 M-Pesa payment gateway
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: candy-common
    version: "0.1.0"
    repository: "file://../candy-common"
