apiVersion: v2
name: icore
description: Icore Django 5.2 + FastAPI core platform
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: candy-common
    version: "0.1.0"
    repository: "file://../candy-common"
