apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-ksa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: "external-secrets-sa@cm-services-prod.iam.gserviceaccount.com"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: cm-services-prod
      auth:
        workloadIdentity:
          clusterLocation: europe-west3
          clusterName: candyplay-prod
          clusterProjectID: cm-services-prod
          serviceAccountRef:
            name: external-secrets-ksa
            namespace: external-secrets
