apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 01tech-env-secret
  namespace: candy-services
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: 01tech-env-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.gcpSecretName }}
