apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tpay-env-secret
  namespace: candy-services
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: tpay-env-secret
    creationPolicy: Owner
  data:
    - secretKey: ".env"
      remoteRef:
        key: {{ .Values.externalSecret.gcpSecretName }}
        version: latest
