---
# Certificate for staging domain api-dev.candyplay.com
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: candyplay-dev-tls
  namespace: candy-services-staging
spec:
  secretName: candyplay-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api-dev.candyplay.com
